name: AuctionHouse
api: 3.0.0-ALPHA11
main: R4KT\AuctionHouse
version: 1.0
author: "R4KT"
authors: ["Skull3x", "Muqsit"]
website: http://github.com/R4KT
commands:
  ah:
    description: ""
    aliases: ["auction", "auctionhouse"]
